import { Project, Stat } from "./types";

export const PORTFOLIO_DATA: { stats: Stat[]; projects: Project[] } = {
    stats: [
        { label: "Real Products Built", value: "5+", color: "bg-red-500", icon: "insights" },
        { label: "Active Projects", value: "3", color: "bg-green-500", icon: "code" },
        { label: "Years Experience", value: "2+", color: "bg-blue-500", icon: "school" },
    ],
    projects: [
        {
            id: 1,
            title: "LiftNode - Workout App Stack",
            category: "Mobile Application",
            categoryIcon: "smartphone",
            tag: "Flutter",
            tagIcon: "flutter_dash",
            tagColor: "bg-blue-100 text-blue-700 dark:bg-[#1e3a8a] dark:text-blue-100",
            shortDesc: "Offline-first fitness application focused on privacy and performance, built with Flutter & Dart.",
            longDesc: "LiftNode adalah aplikasi kebugaran yang dirancang untuk pengguna yang mengutamakan privasi. Tidak ada data yang dikirim ke cloud tanpa izin. Fitur termasuk pelacakan set real-time, grafik kemajuan, dan kalkulator 1RM. Dibangun menggunakan arsitektur Clean Architecture untuk skalabilitas.",
            progress: 80,
            progressColor: "bg-blue-500",
            techStack: ["Flutter", "Dart", "SQLite", "Bloc"],
        },
        {
            id: 2,
            title: "LuminaCal - AI Calorie Tracker",
            category: "Android Application",
            categoryIcon: "android",
            tag: "Kotlin / Android",
            tagIcon: "code",
            tagColor: "bg-green-100 text-green-700 dark:bg-[#14532d] dark:text-green-100",
            shortDesc: "AI-powered calorie tracking app using ML-based food recognition, optimized for local Indonesian dishes.",
            longDesc: "LuminaCal menggunakan TensorFlow Lite di perangkat untuk mengenali makanan Indonesia secara instan. Aplikasi ini membantu pengguna melacak asupan kalori harian dengan akurasi tinggi tanpa perlu koneksi internet konstan.",
            progress: 100,
            progressColor: "bg-green-500",
            techStack: ["Kotlin", "Jetpack Compose", "TensorFlow Lite", "Room DB"],
        },
        {
            id: 3,
            title: "Kelas Kampus Platform Stack",
            category: "Web Platform",
            categoryIcon: "web",
            tag: "Next.js / Tailwind CSS",
            tagIcon: "layers",
            tagColor: "bg-gray-100 text-gray-700 dark:bg-[#333333] dark:text-white",
            shortDesc: "Integrated SNBT preparation platform with CBT simulation, analytics dashboard, and responsive web interface.",
            longDesc: "Platform pendidikan komprehensif untuk persiapan masuk universitas. Memiliki fitur Tryout CBT yang mirip aslinya, analisis butir soal, dan dashboard progres siswa yang detail.",
            progress: 100,
            progressColor: "bg-purple-500",
            techStack: ["Next.js", "React", "PostgreSQL", "Tailwind CSS"],
        },
        {
            id: 4,
            title: "Dzakwan Portfolio V1",
            category: "Web Design",
            categoryIcon: "web",
            tag: "HTML / CSS",
            tagIcon: "html",
            tagColor: "bg-orange-100 text-orange-700 dark:bg-[#431407] dark:text-orange-100",
            shortDesc: "Portofolio versi pertama yang dibuat dengan HTML5 dan CSS3 murni tanpa framework.",
            longDesc: "Langkah awal dalam perjalanan web development. Fokus pada semantik HTML dan layout CSS Flexbox/Grid.",
            progress: 100,
            progressColor: "bg-orange-500",
            techStack: ["HTML5", "CSS3", "Javascript"],
        },
    ]
};
